apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-labels
  labels:
    kind: api
    target: dev
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
