apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nging-pod
  name: nging-pod
spec:
  containers:
  - image: nginx
    name: nging-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
